on:
  push:
  pull_request:
name: Type checker
jobs:
  test:
    name: pyright
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install -e .[gui]
    - uses: jakebailey/pyright-action@v2
      with:
        version: 1.1.318
